In [216]:
# 008/ClassificationRegression-11si/Classification/IRISDatasetDecisionTree.ipynb

In [217]:
from sklearn.preprocessing import Binarizer
import numpy as np
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
import scipy.stats as stats
from binance.enums import HistoricalKlinesType
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

from main_funcs import get_and_update_data


In [218]:
df_source = get_and_update_data("ETHBTC", "4h", HistoricalKlinesType.SPOT, "Germany")
df_source = df_source[["open", "high", "low", "close","volume" ]]
# df_source = df_source.iloc[:-4,:]
df_source

Start Time: 2001-01-01 00:00:00
IP from 'Germany' . its OK!
start get data from binance: 2023-11-13 21:59:41.180265
Getting Data ...
finish get data from binance: 2023-11-13 22:00:09.723621
13865 radif data gerefte shod az binance
tamam radifha ezafe shod


open      high       low     close      volume
open_time                                                              
2017-07-14 07:30:00  0.080000  0.088669  0.080000  0.088591    646.1500
2017-07-14 11:30:00  0.086252  0.089273  0.086252  0.088817    209.1780
2017-07-14 15:30:00  0.088657  0.088817  0.086288  0.086288    383.6310
2017-07-14 19:30:00  0.085999  0.088712  0.085477  0.088500    252.5290
2017-07-14 23:30:00  0.089000  0.091033  0.089000  0.090993    450.5690
...                       ...       ...       ...       ...         ...
2023-11-12 23:30:00  0.055230  0.055550  0.054970  0.055160   4244.3605
2023-11-13 03:30:00  0.055160  0.055680  0.055080  0.055240   6057.0185
2023-11-13 07:30:00  0.055250  0.055520  0.055120  0.055430   5730.5994
2023-11-13 11:30:00  0.055410  0.055690  0.055410  0.055610   5679.1888
2023-11-13 15:30:00  0.055610  0.057200  0.055550  0.057160  19912.0088

[13865 rows x 5 columns]

In [219]:
df = df_source.copy()
df["open_close"] = df.close - df.open
df["open_close_percent"] = df.open_close / df.open
period = 60
for i in range(1,period+1):
    df[f"open_close_percent_{i}"] = df.shift(i).open_close_percent

df["target"] = df.shift(-1).open_close_percent
darsad=0.0
df["target"] = np.where(df['target'] > darsad, 1, np.where(df['target'] < -darsad, -1, 0))
# df["target2"] = np.where( (df['target'] <  0.02) and (df['target'] > -0.02),0, 0 )
# df.dropna(inplace=True)
df.dropna(subset=[f'open_close_percent_{period}'],inplace=True)
df.drop(columns=['open','high','low','close','volume','open_close'],inplace=True)

df

open_close_percent  open_close_percent_1  \
open_time                                                       
2017-07-24 07:30:00           -0.005547             -0.005285   
2017-07-24 11:30:00           -0.005742             -0.005547   
2017-07-24 15:30:00           -0.000265             -0.005742   
2017-07-24 19:30:00            0.000205             -0.000265   
2017-07-24 23:30:00            0.001180              0.000205   
...                                 ...                   ...   
2023-11-12 23:30:00           -0.001267             -0.002709   
2023-11-13 03:30:00            0.001450             -0.001267   
2023-11-13 07:30:00            0.003258              0.001450   
2023-11-13 11:30:00            0.003609              0.003258   
2023-11-13 15:30:00            0.027873              0.003609   

                     open_close_percent_2  open_close_percent_3  \
open_time                                                         
2017-07-24 07:30:00             -0.003959              0.013642   
2017-07-24 11:30:00             -0.005285             -0.003959   
2017-07-24 15:30:00             -0.005547             -0.005285   
2017-07-24 19:30:00             -0.005742             -0.005547   
2017-07-24 23:30:00             -0.000265             -0.005742   
...                                   ...                   ...   
2023-11-12 23:30:00              0.002353             -0.003247   
2023-11-13 03:30:00             -0.002709              0.002353   
2023-11-13 07:30:00             -0.001267             -0.002709   
2023-11-13 11:30:00              0.001450             -0.001267   
2023-11-13 15:30:00              0.003258              0.001450   

                     open_close_percent_4  open_close_percent_5  \
open_time                                                         
2017-07-24 07:30:00              0.000652             -0.002656   
2017-07-24 11:30:00              0.013642              0.000652   
2017-07-24 15:30:00             -0.003959              0.013642   
2017-07-24 19:30:00             -0.005285             -0.003959   
2017-07-24 23:30:00             -0.005547             -0.005285   
...                                   ...                   ...   
2023-11-12 23:30:00             -0.000721              0.003256   
2023-11-13 03:30:00             -0.003247             -0.000721   
2023-11-13 07:30:00              0.002353             -0.003247   
2023-11-13 11:30:00             -0.002709              0.002353   
2023-11-13 15:30:00             -0.001267             -0.002709   

                     open_close_percent_6  open_close_percent_7  \
open_time                                                         
2017-07-24 07:30:00             -0.003234              0.004629   
2017-07-24 11:30:00             -0.002656             -0.003234   
2017-07-24 15:30:00              0.000652             -0.002656   
2017-07-24 19:30:00              0.013642              0.000652   
2017-07-24 23:30:00             -0.003959              0.013642   
...                                   ...                   ...   
2023-11-12 23:30:00             -0.010379              0.001254   
2023-11-13 03:30:00              0.003256             -0.010379   
2023-11-13 07:30:00             -0.000721              0.003256   
2023-11-13 11:30:00             -0.003247             -0.000721   
2023-11-13 15:30:00              0.002353             -0.003247   

                     open_close_percent_8  open_close_percent_9  ...  \
open_time                                                        ...   
2017-07-24 07:30:00              0.023251              0.000112  ...   
2017-07-24 11:30:00              0.004629              0.023251  ...   
2017-07-24 15:30:00             -0.003234              0.004629  ...   
2017-07-24 19:30:00             -0.002656             -0.003234  ...   
2017-07-24 23:30:00              0.000652             -0.002656  ...   
...                                   ...              

In [220]:
# model

# all ok rows and columns
x_ok = df.iloc[:-1,:-1]
y_ok = df.iloc[:-1,-1:]
# fit data count
num = int(len(df)*0.7)
# fit data
x = x_ok[:num]
y = y_ok[:num]
# fit validator
X = x_ok[num:]
Y = y_ok[num:]


svm_classifier = SVC(random_state=len(x), C=0.5)
svm_classifier.fit(x.to_numpy(), y.to_numpy().ravel())


SVC(C=0.5, random_state=9663)

In [221]:
print(df.iloc[-1:,:-1])
svm_classifier.predict(df.iloc[-1:,:-1])

                     open_close_percent  open_close_percent_1  \
open_time                                                       
2023-11-13 15:30:00            0.027873              0.003609   

                     open_close_percent_2  open_close_percent_3  \
open_time                                                         
2023-11-13 15:30:00              0.003258               0.00145   

                     open_close_percent_4  open_close_percent_5  \
open_time                                                         
2023-11-13 15:30:00             -0.001267             -0.002709   

                     open_close_percent_6  open_close_percent_7  \
open_time                                                         
2023-11-13 15:30:00              0.002353             -0.003247   

                     open_close_percent_8  open_close_percent_9  ...  \
open_time                                                        ...   
2023-11-13 15:30:00             -0.000721             

C:\Users\sajja\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([-1])

In [222]:
Y_RESULT = svm_classifier.predict(X)

C:\Users\sajja\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


In [223]:
print(metrics.classification_report(Y,Y_RESULT))

              precision    recall  f1-score   support

          -1       0.51      0.84      0.64      2114
           0       0.00      0.00      0.00        39
           1       0.50      0.17      0.26      1988

    accuracy                           0.51      4141
   macro avg       0.34      0.34      0.30      4141
weighted avg       0.50      0.51      0.45      4141



C:\Users\sajja\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sajja\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sajja\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [224]:
print(metrics.confusion_matrix(Y,Y_RESULT))

[[1766    0  348]
 [  38    0    1]
 [1642    0  346]]
