In [22]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import TimeDistributed, Dense, LSTM, GRU, SimpleRNN

---
One to One

In [30]:
length = 10
seq = np.array([ i/float(length) for i in range(length)])
X = seq.reshape(len(seq), 1, 1)
y = seq.reshape(len(seq), 1)
n_neuros = length
n_batch = length
n_epoch = 100

In [31]:
X

array([[[0. ]],

       [[0.1]],

       [[0.2]],

       [[0.3]],

       [[0.4]],

       [[0.5]],

       [[0.6]],

       [[0.7]],

       [[0.8]],

       [[0.9]]])

In [3]:
model  = Sequential()
model.add(GRU(n_neuros, input_shape=(1, 1)))
model.add(Dense(1))

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru (GRU)                   (None, 10)                390       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 401
Trainable params: 401
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [6]:
model.fit(X, y, epochs=n_epoch, batch_size=n_batch)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.1452
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 0.1420
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1387
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1355
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1324
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1293
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1262
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1232
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1202
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1172
Epoch 11/100
1/1 [==============================] - 0s 4ms/step - loss: 0.1143
Epoch 12/100
1/1 [==============================] - 0s 5ms/step - loss: 0.1114
Epoch 13/100
1/1 [==============================] - 0s 3ms/ste

Many to One

In [11]:
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length)

In [12]:
X

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [13]:
y

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]])

In [14]:
model  = Sequential()
model.add(GRU(n_neuros, input_shape=(length, 1)))
model.add(Dense(length))

In [15]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_1 (GRU)                 (None, 10)                390       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
Total params: 500
Trainable params: 500
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X, y, epochs=n_epoch, batch_size=n_batch)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.3535
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.3485
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 0.3436
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3387
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 0.3340
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 0.3293
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 0.3248
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 0.3203
Epoch 9/100
1/1 [==============================] - 0s 9ms/step - loss: 0.3159
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 0.3116
Epoch 11/100
1/1 [==============================] - 0s 10ms/step - loss: 0.3074
Epoch 12/100
1/1 [==============================] - 0s 7ms/step - loss: 0.3032
Epoch 13/100
1/1 [==============================] - 0s 10ms/

In [18]:
model.predict(X, batch_size=n_batch)

1/1 [==============================] - 0s 279ms/step


array([[0.00555011, 0.09797401, 0.36132306, 0.28354526, 0.5249488 ,
        0.41239557, 0.4096105 , 0.41158432, 0.33877325, 0.41753557]],
      dtype=float32)

---
Many 2 Many

In [19]:
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)

In [20]:
X

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [21]:
y

array([[[0. ],
        [0.1],
        [0.2],
        [0.3],
        [0.4],
        [0.5],
        [0.6],
        [0.7],
        [0.8],
        [0.9]]])

In [23]:
model  = Sequential()
model.add(GRU(n_neuros, input_shape=(length, 1), return_sequences=True))
model.add(TimeDistributed(Dense(length)))

In [24]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [25]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_2 (GRU)                 (None, 10, 10)            390       
                                                                 
 time_distributed (TimeDistr  (None, 10, 10)           110       
 ibuted)                                                         
                                                                 
Total params: 500
Trainable params: 500
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(X, y, epochs=n_epoch, batch_size=n_batch)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.2570
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2535
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2501
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2467
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2433
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2399
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2365
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2332
Epoch 9/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2298
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2265
Epoch 11/100
1/1 [==============================] - 0s 10ms/step - loss: 0.2232
Epoch 12/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2199
Epoch 13/100
1/1 [==============================] - 0s 8ms/st

In [27]:
model.predict(X, batch_size=n_batch)

1/1 [==============================] - 0s 253ms/step


array([[[0.12866734, 0.11837836, 0.11912172, 0.08359279, 0.12622635,
         0.13425379, 0.15046644, 0.11278322, 0.17254025, 0.16049051],
        [0.19765125, 0.19601613, 0.17373675, 0.17973748, 0.17665032,
         0.2183793 , 0.23473375, 0.19098839, 0.24704896, 0.21433122],
        [0.27296305, 0.28493255, 0.23813197, 0.28870556, 0.2316952 ,
         0.30914354, 0.31609994, 0.28051046, 0.31093466, 0.26048434],
        [0.35057437, 0.37834013, 0.30776665, 0.39883867, 0.28772938,
         0.40266976, 0.39285755, 0.37278974, 0.3700381 , 0.3033995 ],
        [0.42700642, 0.47106692, 0.37900254, 0.5045408 , 0.3421969 ,
         0.49508455, 0.4645887 , 0.4622708 , 0.42664373, 0.34329116],
        [0.49937454, 0.5595386 , 0.44927758, 0.60304   , 0.3934574 ,
         0.5828969 , 0.5309974 , 0.54533345, 0.48123252, 0.3794781 ],
        [0.5655583 , 0.6416136 , 0.5169502 , 0.69315106, 0.44058156,
         0.66338307, 0.5917822 , 0.61989003, 0.5334335 , 0.4114747 ],
        [0.62429297, 0.7163

In [28]:
# MasoudKaviani.ir